services:
  api:
    build: .
    container_name: churn_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  tests:
    build: .
    container_name: churn_tests
    volumes:
      - .:/app
    command: pytest -v

